// src/data/phrases.ts
export const phrases: string[] = [
    'Hello',
    'Thank you',
    'Goodbye',
    'Please',
    'Sorry',
    'Yes',
    'No',
    'Help',
    'Friend',
    'Family',
    'Good morning',
    'Good night',
    'How are you?',
    'I love you',
    'Excuse me',
    'What time is it?',
    'Where is the bathroom?',
    'How much does it cost?',
    'Can you help me?',
    'I don’t understand',
    'Please speak slowly',
    'I need a doctor',
    'I am lost',
    'Can I get the bill?',
    'I am hungry',
    'I am thirsty',
    'I am tired',
    'Do you speak English?',
    'How are you doing?',
    'What is your name?',
    'My name is...',
    'I am from...',
    'I don’t know',
    'I would like...',
    'I am looking for...',
    'Could you recommend...?',
    'I am allergic to...',
    'Where can I find...?',
    'Is it far?',
    'I am a tourist',
    'Can I try it on?',
    'I would like to make a reservation',
    'What is the weather like?',
    'Can you show me?',
    'How do I get to...?',
    'What is the address?',
    'I am here on business',
    'I am here for vacation',
    'Can I have a glass of water?',
    'I need a taxi',
    'Where is the nearest hospital?',
    'Do you have a menu?'
  ];
  