// utils/wordData.ts

interface WordItem {
    word: string;
    hint: string;
  }
  
  export const wordData: Record<string, WordItem[]> = {
    en: [
      { word: 'elephant', hint: 'This massive mammal is known for its trunk and tusks.' },
      { word: 'flower', hint: 'Often seen in gardens, this entity is admired for its petals.' },
      { word: 'watermelon', hint: 'A large, green fruit with a sweet, juicy red interior.' },
      { word: 'pencil', hint: 'A writing tool made of wood, often used in classrooms.' },
      { word: 'coffee', hint: 'A popular beverage made from roasted beans, usually consumed in the morning.' },
      { word: 'happy', hint: 'An emotion characterized by joy and satisfaction.' },
      { word: 'face', hint: 'The front part of the head where the eyes, nose, and mouth are located.' },
      { word: 'snake', hint: 'A legless reptile known for slithering and sometimes venomous.' },
      { word: 'pendulum', hint: 'An object swinging back and forth, often used in clocks.' },
      { word: 'pillow', hint: 'A soft cushion used for resting the head during sleep.' },
    ],
    es: [
      { word: 'elefante', hint: 'Este enorme mamífero es conocido por su trompa y colmillos.' },
      { word: 'flor', hint: 'A menudo vista en jardines, esta entidad es admirada por sus pétalos.' },
      { word: 'sandía', hint: 'Una fruta grande y verde con un interior rojo y jugoso.' },
      { word: 'lápiz', hint: 'Una herramienta de escritura hecha de madera, a menudo usada en las aulas.' },
      { word: 'café', hint: 'Una bebida popular hecha de granos tostados, generalmente consumida en la mañana.' },
      { word: 'feliz', hint: 'Una emoción caracterizada por la alegría y satisfacción.' },
      { word: 'cara', hint: 'La parte frontal de la cabeza donde se encuentran los ojos, la nariz y la boca.' },
      { word: 'serpiente', hint: 'Un reptil sin patas conocido por deslizarse y a veces venenoso.' },
      { word: 'péndulo', hint: 'Un objeto que oscila hacia adelante y hacia atrás, a menudo usado en relojes.' },
      { word: 'almohada', hint: 'Un cojín suave usado para descansar la cabeza durante el sueño.' },
    ],
    fr: [
      { word: 'éléphant', hint: 'Ce grand mammifère est connu pour sa trompe et ses précieuses défenses.' },
      { word: 'fleur', hint: 'Souvent vue dans les jardins, cette entité est appréciée pour ses pétales colorés.' },
      { word: 'pastèque', hint: 'Un fruit volumineux et vert avec une chair rouge sucrée à l’intérieur.' },
      { word: 'crayon', hint: 'Un outil d’écriture en bois, souvent utilisé dans les écoles.' },
      { word: 'café', hint: 'Une boisson populaire fabriquée à partir de grains torréfiés, souvent consommée le matin.' },
      { word: 'heureux', hint: 'Un sentiment de joie et de satisfaction.' },
      { word: 'visage', hint: 'La partie avant de la tête où se trouvent les yeux, le nez et la bouche.' },
      { word: 'serpent', hint: 'Un reptile sans pattes connu pour se faufiler et parfois venimeux.' },
      { word: 'pendule', hint: 'Un objet qui oscille d’avant en arrière, souvent utilisé dans les horloges.' },
      { word: 'oreiller', hint: 'Un coussin doux utilisé pour reposer la tête pendant le sommeil.' },
    ],
    de: [
      { word: 'elefant', hint: 'Dieses große Säugetier ist bekannt für seinen Rüssel und seine Stoßzähne.' },
      { word: 'blume', hint: 'Oft in Gärten zu finden, wird dieses Wesen wegen seiner Blütenblätter geschätzt.' },
      { word: 'wassermelone', hint: 'Eine große, grüne Frucht mit einem süßen, roten Inneren.' },
      { word: 'stift', hint: 'Ein Schreibwerkzeug aus Holz, das oft in Klassenzimmern verwendet wird.' },
      { word: 'kaffee', hint: 'Ein beliebtes Getränk aus gerösteten Bohnen, das oft morgens getrunken wird.' },
      { word: 'glücklich', hint: 'Ein Gefühl der Freude und Zufriedenheit.' },
      { word: 'gesicht', hint: 'Der vordere Teil des Kopfes, auf dem Augen, Nase und Mund liegen.' },
      { word: 'schlange', hint: 'Ein beinloses Reptil, das sich schlängelt und manchmal giftig ist.' },
      { word: 'pendel', hint: 'Ein schwingendes Objekt, das oft in Uhren verwendet wird.' },
      { word: 'kissen', hint: 'Ein weiches Polster, das zum Ausruhen des Kopfes beim Schlafen verwendet wird.' },
    ],
    it: [
      { word: 'elefante', hint: 'Questo grande mammifero è noto per la sua proboscide e le sue zanne.' },
      { word: 'fiore', hint: 'Spesso visto nei giardini, questo oggetto è ammirato per i suoi petali.' },
      { word: 'anguria', hint: 'Un grande frutto verde con un interno rosso dolce.' },
      { word: 'matita', hint: 'Uno strumento di scrittura in legno, spesso usato nelle scuole.' },
      { word: 'caffè', hint: 'Una bevanda popolare fatta con chicchi tostati, solitamente bevuta al mattino.' },
      { word: 'felice', hint: 'Una emozione caratterizzata da gioia e soddisfazione.' },
      { word: 'viso', hint: 'La parte anteriore della testa dove si trovano gli occhi, il naso e la bocca.' },
      { word: 'serpente', hint: 'Un rettile senza zampe noto per strisciare e talvolta velenoso.' },
      { word: 'pendolo', hint: 'Un oggetto che oscilla avanti e indietro, spesso usato negli orologi.' },
      { word: 'cuscino', hint: 'Un cuscinetto morbido usato per appoggiare la testa durante il sonno.' },
    ],
    pt: [
      { word: 'elefante', hint: 'Este grande mamífero é conhecido pela sua tromba e presas.' },
      { word: 'flor', hint: 'Frequentemente vista em jardins, essa entidade é admirada por suas pétalas.' },
      { word: 'melancia', hint: 'Uma grande fruta verde com um interior vermelho e doce.' },
      { word: 'lápis', hint: 'Uma ferramenta de escrita feita de madeira, frequentemente usada em escolas.' },
      { word: 'café', hint: 'Uma bebida popular feita de grãos torrados, geralmente consumida de manhã.' },
      { word: 'feliz', hint: 'Uma emoção caracterizada por alegria e satisfação.' },
      { word: 'rosto', hint: 'A parte frontal da cabeça onde estão os olhos, o nariz e a boca.' },
      { word: 'cobra', hint: 'Um réptil sem patas conhecido por rastejar e às vezes venenoso.' },
      { word: 'pêndulo', hint: 'Um objeto que oscila para frente e para trás, frequentemente usado em relógios.' },
      { word: 'travesseiro', hint: 'Um almofada macia usada para descansar a cabeça durante o sono.' },
    ],
    ru: [
      { word: 'слон', hint: 'Это большое млекопитающее известно своим хоботом и клыками.' },
      { word: 'цветок', hint: 'Часто встречается в садах, это существо восхищает своими лепестками.' },
      { word: 'арбуз', hint: 'Большой зелёный фрукт с сладкой красной мякотью.' },
      { word: 'карандаш', hint: 'Инструмент для письма, сделанный из дерева, часто используемый в школах.' },
      { word: 'кофе', hint: 'Популярный напиток из обжаренных зёрен, обычно употребляемый по утрам.' },
      { word: 'счастливый', hint: 'Эмоция, характеризующаяся радостью и удовлетворением.' },
      { word: 'лицо', hint: 'Передняя часть головы, где находятся глаза, нос и рот.' },
      { word: 'змея', hint: 'Безногие рептилии, известные своим ползанием и иногда ядовитые.' },
      { word: 'маятник', hint: 'Объект, качающийся взад и вперед, часто используемый в часах.' },
      { word: 'подушка', hint: 'Мягкая подушка, используемая для отдыха головы во время сна.' },
    ],
    ja: [
      { word: '象', hint: 'この大きな哺乳類は、その鼻と牙で知られています。' },
      { word: '花', hint: '庭でよく見られるこの存在は、その花びらで称賛されます。' },
      { word: 'スイカ', hint: '大きな緑の果物で、中は甘い赤い果肉が入っています。' },
      { word: '鉛筆', hint: '木でできた書き物用具で、教室でよく使用されます。' },
      { word: 'コーヒー', hint: '焙煎された豆から作られる人気の飲み物で、通常は朝に飲まれます。' },
      { word: '幸せ', hint: '喜びと満足感を特徴とする感情です。' },
      { word: '顔', hint: '目、鼻、口がある頭の前面です。' },
      { word: 'ヘビ', hint: '脚がない爬虫類で、時には毒があります。' },
      { word: '振り子', hint: '前後に揺れる物体で、時計に使われることがよくあります。' },
      { word: '枕', hint: '寝るときに頭を支えるために使う柔らかいクッションです。' },
    ],
    zh: [
      { word: '大象', hint: '这种大型哺乳动物以其长鼻子和象牙而闻名。' },
      { word: '花', hint: '常见于花园，这种存在因其花瓣而受到赞赏。' },
      { word: '西瓜', hint: '一种大型绿色水果，内部是甜美的红色果肉。' },
      { word: '铅笔', hint: '一种木制的书写工具，通常在教室中使用。' },
      { word: '咖啡', hint: '一种用烘焙豆制成的流行饮料，通常在早晨饮用。' },
      { word: '快乐', hint: '一种以喜悦和满足感为特点的情感。' },
      { word: '脸', hint: '头部前面的部分，有眼睛、鼻子和嘴巴。' },
      { word: '蛇', hint: '一种无腿的爬行动物，通常会爬行，有时还会有毒。' },
      { word: '摆钟', hint: '一种前后摆动的物体，通常用于钟表中。' },
      { word: '枕头', hint: '用于睡觉时支撑头部的柔软垫子。' },
    ],
    ar: [
      { word: 'فيل', hint: 'هذا الثديي الكبير معروف بأنفه الطويل وأنيابه.' },
      { word: 'زهرة', hint: 'تُرى غالباً في الحدائق، وتُعجب بسبب بتلاتها.' },
      { word: 'بطيخ', hint: 'فاكهة كبيرة وخضراء مع لب أحمر حلو من الداخل.' },
      { word: 'قلم', hint: 'أداة كتابة مصنوعة من الخشب، تُستخدم غالباً في الفصول الدراسية.' },
      { word: 'قهوة', hint: 'مشروب شعبي مصنوع من حبوب محمصة، يُستهلك عادة في الصباح.' },
      { word: 'سعيد', hint: 'شعور بالفرح والرضا.' },
      { word: 'وجه', hint: 'الجزء الأمامي من الرأس حيث توجد العينان والأنف والفم.' },
      { word: 'ثعبان', hint: 'زواحف بلا أرجل معروفة بالزحف وأحياناً سامة.' },
      { word: 'البندول', hint: 'جسم يتأرجح ذهاباً وإياباً، وغالباً ما يُستخدم في الساعات.' },
      { word: 'وسادة', hint: 'وسادة ناعمة تُستخدم لدعم الرأس أثناء النوم.' },
    ],
    ko: [
      { word: '코끼리', hint: '이 큰 포유류는 긴 코와 상아로 유명합니다.' },
      { word: '꽃', hint: '정원에서 자주 볼 수 있으며, 꽃잎으로 칭찬받습니다.' },
      { word: '수박', hint: '큰 초록색 과일로, 안에는 달콤한 빨간 과육이 있습니다.' },
      { word: '연필', hint: '나무로 만들어진 쓰기 도구로, 종종 교실에서 사용됩니다.' },
      { word: '커피', hint: '볶은 원두로 만든 인기 있는 음료로, 보통 아침에 마십니다.' },
      { word: '행복', hint: '기쁨과 만족감을 특징으로 하는 감정입니다.' },
      { word: '얼굴', hint: '눈, 코, 입이 있는 머리의 앞부분입니다.' },
      { word: '뱀', hint: '다리가 없는 파충류로, 기어다니며 때로는 독이 있습니다.' },
      { word: '진자', hint: '앞뒤로 흔들리는 물체로, 시계에서 사용됩니다.' },
      { word: '베개', hint: '잠잘 때 머리를 받치기 위해 사용하는 부드러운 쿠션입니다.' },
    ],
    hi: [
      { word: 'हाथी', hint: 'यह बड़ा स्तनधारी अपने लंबे सुँड और दांतों के लिए जाना जाता है।' },
      { word: 'फूल', hint: 'आमतौर पर बागों में देखा जाता है, इसकी पंखुड़ियों के लिए सराहा जाता है।' },
      { word: 'तरबूज', hint: 'एक बड़ा हरा फल, जिसका अंदर का भाग मीठा लाल होता है।' },
      { word: 'पेंसिल', hint: 'लकड़ी से बनी लेखन की वस्तु, अक्सर स्कूलों में इस्तेमाल होती है।' },
      { word: 'कॉफ़ी', hint: 'भुने हुए बीन्स से बनी लोकप्रिय पेय, आमतौर पर सुबह पी जाती है।' },
      { word: 'खुश', hint: 'आनंद और संतोष की भावना।' },
      { word: 'चेहरा', hint: 'सिर का सामने वाला हिस्सा जहां आंखें, नाक और मुँह होते हैं।' },
      { word: 'साँप', hint: 'पैरों के बिना एक सरीसृप, जो रेंगता है और कभी-कभी विषैला होता है।' },
      { word: 'पेंडुलम', hint: 'एक वस्तु जो आगे-पीछे हिलती है, अक्सर घड़ियों में इस्तेमाल होती है।' },
      { word: 'तकिया', hint: 'सोते समय सिर को सहारा देने के लिए उपयोग की जाने वाली मुलायम कुशन।' },
    ],
    th: [
      { word: 'ช้าง', hint: 'สัตว์เลี้ยงลูกด้วยนมขนาดใหญ่ที่รู้จักกันดีด้วยงาและคอยาวของมัน.' },
      { word: 'ดอกไม้', hint: 'มักเห็นในสวน ซึ่งสิ่งนี้ได้รับการชื่นชมจากกลีบของมัน.' },
      { word: 'แตงโม', hint: 'ผลไม้ขนาดใหญ่สีเขียวที่มีเนื้อแดงหวานภายใน.' },
      { word: 'ดินสอ', hint: 'เครื่องมือสำหรับเขียนทำจากไม้ ใช้บ่อยในห้องเรียน.' },
      { word: 'กาแฟ', hint: 'เครื่องดื่มที่ทำจากเมล็ดคั่วที่นิยมดื่มในตอนเช้า.' },
      { word: 'มีความสุข', hint: 'ความรู้สึกที่มีความสุขและพอใจ.' },
      { word: 'ใบหน้า', hint: 'ส่วนหน้าของหัวที่มีตา จมูก และปาก.' },
      { word: 'งู', hint: 'สัตว์เลื้อยคลานที่ไม่มีขา รู้จักกันดีในเรื่องการคลานและบางครั้งมีพิษ.' },
      { word: 'ลูกตุ้ม', hint: 'วัตถุที่แกว่งไปมา มักใช้ในนาฬิกา.' },
      { word: 'หมอน', hint: 'เบาะนุ่มที่ใช้รองศีรษะขณะนอนหลับ.' },
    ],
    pl: [
      { word: 'słoń', hint: 'To duże ssaki jest znane ze swojego trąby i kłów.' },
      { word: 'kwiat', hint: 'Często widziany w ogrodach, podziwiany za swoje płatki.' },
      { word: 'arbuz', hint: 'Duży zielony owoc z soczystym czerwonym wnętrzem.' },
      { word: 'ołówek', hint: 'Narzędzie do pisania z drewna, często używane w szkołach.' },
      { word: 'kawa', hint: 'Popularny napój z palonych ziaren, zwykle pijany rano.' },
      { word: 'szczęśliwy', hint: 'Emocja charakteryzująca się radością i satysfakcją.' },
      { word: 'twarz', hint: 'Przednia część głowy, na której znajdują się oczy, nos i usta.' },
      { word: 'wąż', hint: 'Beznogie gady, znane z pełzania i czasami jadowite.' },
      { word: 'wahadło', hint: 'Obiekt kołyszący się w przód i w tył, często używany w zegarach.' },
      { word: 'poduszka', hint: 'Miękka poduszka używana do podpierania głowy podczas snu.' },
    ],
  };
  